#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace components::table {

    enum class table_constraint_type : uint8_t
    {
        PRIMARY_KEY,
        UNIQUE,
        CHECK,
        FOREIGN_KEY
    };

    // Field order: vectors → strings → enum/char flags, to minimise padding.
    struct table_constraint_t {
        std::vector<std::string> columns;
        std::vector<std::string> ref_columns; // matching column names in referenced table
        std::string check_expression;         // only for CHECK (raw SQL text)
        // FK fields — only meaningful when type == FOREIGN_KEY:
        std::string ref_database;   // referenced table's database (empty = same as child)
        std::string ref_collection; // referenced table name
        std::string name;           // optional constraint name (autogenerated when empty)
        table_constraint_type type;
        // FK semantic flags (PostgreSQL FKCONSTR_* alphabet) — defaults match SQL standard:
        char fk_matchtype{'s'};  // 's' SIMPLE / 'f' FULL / 'p' PARTIAL
        char fk_del_action{'a'}; // 'a' NO ACTION / 'r' RESTRICT / 'c' CASCADE / 'n' SET NULL / 'd' SET DEFAULT
        char fk_upd_action{'a'}; // same alphabet as fk_del_action
    };
    // Layout guard: libstdc++ (string==32) → 184; libc++ (string==24) → 152.
    static_assert(sizeof(table_constraint_t) <= 184, "table_constraint_t layout regression");

} // namespace components::table
