name: ubuntu 22.04

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  run:
    name: Run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt update && sudo apt install -y  build-essential ninja-build python3-pip curl gnupg apt-transport-https flex bison git

      - name: conan installation and configuration
        run: |
          python3 -m pip install conan==2.20.0
          conan profile detect --force
          git clone --depth 1 https://github.com/duckstax/conan-duckstax.git /tmp/conan-duckstax
          conan remote add duckstax /tmp/conan-duckstax --type=local-recipes-index

      - name: download dependencies
        run: |
          mkdir build && cd build
          cp ../conanfile.py .
          conan install . --build missing -s build_type=Release -s compiler.cppstd=20

      - name: build
        env:
          CC: gcc
        run: |
          cd build
          cmake  -G Ninja -DCMAKE_TOOLCHAIN_FILE=./build/Release/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DDEV_MODE=ON -DEXAMPLE=ON ..
          cmake --build .

      - name: Test
        run: |
          cd build
          ctest -C Release -V --output-on-failure
